spring.application.name=FER
# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://127.0.0.1:6432/FER
spring.datasource.username=graduate
spring.datasource.password=whfdjqgkqtlek2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA (?? DB ??) =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== Timezone (??) =====
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# ===== JWT =====
security.jwt.issuer=fer-api
security.jwt.secret=PLEASE_CHANGE_TO_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS
security.jwt.access-ttl-seconds=900
security.jwt.refresh-ttl-seconds=1209600
